import Form from '@/components/Form';
import UsersList from '@/components/UsersList';
import Head from 'next/head';
import { useCallback, useState } from 'react';

export default function Home() {
	const [usersList, setUsersList] = useState([]);

	const addUser = useCallback((newUser) => {
		// assign a random id so we have a key for the list entries
		setUsersList([...usersList, { id: usersList.length, ...newUser }]);
	}, [usersList]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container">
				<div className="row pt-3">
					<div className="col-sm mb-5">
						<Form onSubmit={addUser} ></Form>
					</div>
					<div className="col d-flex flex-column align-items-center">
						{Boolean(usersList.length) &&
							<UsersList usersList={usersList} ></UsersList>
						}
					</div>
				</div>
			</main>
		</>
	);
}